name: Build and test master
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/nike4613/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build projects
        run: dotnet build --configuration Release -clp:NoSummary
      - name: Run tests
        run: dotnet test MathExprTests -c Release --collect:"XPlat Code Coverage"  -clp:NoSummary
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: MathExprTests/TestResults
      - name: Pack Nuget package
        shell: pwsh
        run: dotnet pack -c Release MathExpr --version-suffix (Get-date -UFormat "nightly.%y%m%d%H%M") -p:InformationalVersion="GitHub Actions CI" -clp:NoSummary
      - name: Push Nupkg to GitHub Packages
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path: MathExpr/bin/Release/*.nupkg
          repo-owner: nike4613
          gh-user: nike4613
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push SNupkg to GitHub Packages
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path: MathExpr/bin/Release/*.snupkg
          repo-owner: nike4613
          gh-user: nike4613
          skip-duplicate: false
          token: ${{ secrets.GITHUB_TOKEN }}