name: Build and test master
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.301' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/nike4613/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build projects
        run: dotnet build --configuration Release
      - name: Run tests
        run: dotnet test MathExprTests --configuration Release --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: MathExprTests/TestResults
      - name: Pack Nuget package
        shell: pwsh
        run: dotnet pack --configuration Release MathExpr --version-suffix (Get-date -UFormat "nightly.%y%m%d%H%M") -p:InformationalVersion="GitHub Actions CI" --include-symbols
      - name: Publish Nuget package to GitHub Packages
        run: dotnet nuget push MathExpr/bin/Release/*.nupkg
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}